# YouTube 视频转文本配置文件

# 下载配置
download:
  output_dir: "output/videos"          # 视频保存目录
  format: "best[height<=720]"          # 视频格式 (720p以下)
  audio_only: false                    # 是否仅下载音频（仅对 YouTube 有效）
  audio_format: "mp3"                  # 音频格式
  audio_quality: "192k"                # 音频质量
  copy_local_files: true               # 是否复制本地文件到输出目录

# 转换配置
converter:
  output_dir: "output/audios"          # 音频保存目录
  audio_format: "mp3"                  # 音频格式
  quality: "192k"                      # 音频质量
  channels: 1                          # 声道数 (1=单声道, 2=立体声)

# 转录配置
transcriber:
  output_dir: "output/texts"           # 文本保存目录
  model_size: "base"                   # Whisper模型大小 (tiny, base, small, medium, large)
  language: null                       # 语言代码 (null=自动检测, zh=中文, en=英文)
  task: "transcribe"                   # 任务类型 (transcribe=转录, translate=翻译)

# 格式化配置
formatter:
  output_dir: "output/formatted"       # 格式化文档保存目录
  enable_basic_formatting: true        # 启用基础排版
  enable_ai_enhancement: false         # 启用AI增强排版 (可选)
  ai_service: "local"                  # AI服务类型 (local/openai/claude)
  output_formats: ["markdown"]         # 输出格式 (markdown/html/pdf)

# 日志配置
logging:
  level: "INFO"                        # 日志级别 (DEBUG, INFO, WARNING, ERROR)
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"
  file: "logs/app.log"                 # 日志文件路径
